apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - podinfo
  selector:
    matchLabels:
      app: podinfo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
